name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_deploy:
    name: Build and Deploy Website to S3
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: |
          npm install

      - name: Inject secret variables into .env file
        run: |
          echo "VITE_API_KEY=${{ secrets.MAPBOX_TOKEN }}" >> .env
          echo "VITE_WEBHOOK_GET_POINT=${{ secrets.WEBHOOK_GET }}" >> .env
          echo "VITE_WEBHOOK_GET_EVENT=${{ secrets.WEBHOOK_GET_EVENT }}" >> .env
          echo "VITE_WEBHOOK_PUT=${{ secrets.WEBHOOK_PUT }}" >> .env

      - name: Build Website
        run: npm run build

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Deploy to S3
        run: |
          run: |
          aws s3 sync ./dist/ s3://mobility-map-website/ --delete --acl public-read \
            --exclude "*.html" --exclude "*.css" --include "*.js" --content-type "application/javascript"

          aws s3 sync ./dist/ s3://mobility-map-website/ --delete --acl public-read \
            --exclude "*.html" --exclude "*.js" --include "*.css" --content-type "text/css"

          aws s3 sync ./dist/ s3://mobility-map-website/ --delete --acl public-read \
            --exclude "*.js" --exclude "*.css" --include "*.html" --content-type "text/html"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "us-east-2"

      - name: Deploy to Amplify
        run: |
          aws amplify start-deployment \
            --app-id ${{ secrets.APP_ID }} \
            --branch-name main \
            --region us-east-2 \
            --source-url s3://mobility-map-website/ \
            --source-url-type BUCKET_PREFIX